// GENERATED DEPLOYMENT MIRROR. Canonical source is private marketing-superpowers runtime.
const encoder=new TextEncoder();
const ALLOWED=new Set(['github.create_issue','github.create_branch','github.create_pull_request','github.create_file_branch','github.update_file_branch']);
const MANUAL=new Set(['github.merge_pull_request','github.force_update_branch','github.delete_branch','github.delete_file','github.delete_repository','github.archive_repository','github.transfer_repository','github.remove_branch_protection']);
function stable(v){if(Array.isArray(v))return v.map(stable);if(v&&typeof v==='object')return Object.fromEntries(Object.keys(v).sort().map(k=>[k,stable(v[k])]));return v;}
const canonical=v=>JSON.stringify(stable(v));
function b64(bytes){let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/g,'');}
function unb64(v){const p=v.replace(/-/g,'+').replace(/_/g,'/')+'==='.slice((v.length+3)%4);const s=atob(p);return Uint8Array.from(s,c=>c.charCodeAt(0));}
async function sha(v){return b64(new Uint8Array(await crypto.subtle.digest('SHA-256',encoder.encode(v))));}
async function key(secret,usage){return crypto.subtle.importKey('raw',encoder.encode(secret),{name:'HMAC',hash:'SHA-256'},false,[usage]);}
async function sign(secret,v){return b64(new Uint8Array(await crypto.subtle.sign('HMAC',await key(secret,'sign'),encoder.encode(v))));}
async function verify(secret,v,sig){return crypto.subtle.verify('HMAC',await key(secret,'verify'),unb64(sig),encoder.encode(v));}
function targetError(op,t={}){if(!/^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/.test(String(t.repository||'')))return'target.repository must be owner/repo';if(op==='github.create_branch'&&(!t.branch||!t.from_ref))return'create_branch requires target.branch and target.from_ref';if(op==='github.create_pull_request'&&(!t.head||!t.base))return'create_pull_request requires target.head and target.base';if(op==='github.create_file_branch'||op==='github.update_file_branch'){const b=String(t.branch||'');if(!b||!t.path)return'file write requires target.branch and target.path';if(['main','master'].includes(b.toLowerCase()))return'default-branch direct file writes are not allowed in standard approval lane';}return null;}
export function classifyApprovalOperation(op){if(MANUAL.has(op))return{allowed:false,tier:'manual_only',reason:'manual_only_operation'};if(!ALLOWED.has(op))return{allowed:false,tier:'unsupported',reason:'operation_not_allowlisted'};return{allowed:true,tier:'standard_approval'};}
export async function prepareApprovalRequest(input){const operation=String(input?.operation||'');const c=classifyApprovalOperation(operation);if(!c.allowed)return{ok:false,error:c.reason,tier:c.tier};const target=stable(input?.target||{});const e=targetError(operation,target);if(e)return{ok:false,error:'invalid_target',detail:e};const args=stable(input?.args||{});const approval_request={version:1,operation,target,args,tier:c.tier};const fingerprint=await sha(canonical(approval_request));return{ok:true,approval_request,fingerprint,confirmation_required:true,confirmation_phrase:`APPROVE ${fingerprint}`,delete_permitted:false,archive_permitted:false};}
export async function issueApprovalGrant(input,secret,nowMs=Date.now()){if(!secret)return{ok:false,error:'approval_secret_not_configured'};const p=await prepareApprovalRequest(input?.approval_request);if(!p.ok)return p;if(String(input?.confirmation||'')!==p.confirmation_phrase)return{ok:false,error:'confirmation_mismatch',fingerprint:p.fingerprint};const ttl=Math.max(60,Math.min(Number(input?.ttl_seconds||300),600));const payload={v:1,fp:p.fingerprint,op:p.approval_request.operation,target:p.approval_request.target,iat:Math.floor(nowMs/1000),exp:Math.floor(nowMs/1000)+ttl,jti:crypto.randomUUID()};const encoded=b64(encoder.encode(canonical(payload)));return{ok:true,approval_grant:`${encoded}.${await sign(secret,encoded)}`,expires_at:payload.exp,fingerprint:payload.fp,operation:payload.op,target:payload.target,single_operation_scope:true,replay_protection:'durable_object_single_use_consumption'};}
export async function validateApprovalGrant(token,expectedInput,secret,nowMs=Date.now()){if(!secret)return{ok:false,error:'approval_secret_not_configured'};const [encoded,sig,extra]=String(token||'').split('.');if(!encoded||!sig||extra)return{ok:false,error:'invalid_grant_format'};if(!(await verify(secret,encoded,sig)))return{ok:false,error:'invalid_grant_signature'};let payload;try{payload=JSON.parse(new TextDecoder().decode(unb64(encoded)));}catch{return{ok:false,error:'invalid_grant_payload'};}if(!payload.exp||Math.floor(nowMs/1000)>payload.exp)return{ok:false,error:'approval_grant_expired'};const p=await prepareApprovalRequest(expectedInput);if(!p.ok)return p;if(payload.fp!==p.fingerprint||payload.op!==p.approval_request.operation)return{ok:false,error:'approval_scope_mismatch'};return{ok:true,approved:true,fingerprint:payload.fp,operation:payload.op,target:payload.target,jti:payload.jti,expires_at:payload.exp,delete_permitted:false,archive_permitted:false,execution_enabled:false,block_reason:'approval_must_be_consumed_once_before_executor_enablement'};}
export async function consumeApprovalGrant(token,expectedInput,secret,ledger,nowMs=Date.now()){if(!ledger||typeof ledger.consume!=='function')return{ok:false,error:'approval_consumption_ledger_not_configured'};const v=await validateApprovalGrant(token,expectedInput,secret,nowMs);if(!v.ok)return v;const c=await ledger.consume({jti:v.jti,fingerprint:v.fingerprint,operation:v.operation,expires_at:v.expires_at});if(!c?.ok)return c||{ok:false,error:'approval_consumption_failed'};return{ok:true,approved:true,consumed:true,fingerprint:v.fingerprint,operation:v.operation,target:v.target,jti:v.jti,expires_at:v.expires_at,consumed_at:c.consumed_at,replay_permitted:false,delete_permitted:false,archive_permitted:false,execution_enabled:false,block_reason:'github_write_executor_not_yet_enabled'};}
