// GENERATED DEPLOYMENT MIRROR. Canonical: lehr007-coder/Listing-Team-Development-Repository/marketing-superpowers/runtime/src/index.js
import { routeRequest } from './router.js';
import { projects, capabilities, policies } from './registry.js';
import { prepareApprovalRequest, issueApprovalGrant, validateApprovalGrant, consumeApprovalGrant } from './approval.js';
import { executeApprovedGithubWrite } from './github-write-executor.js';
import { githubWriteAdapter } from './github-write-adapter.js';
import { validateGithubWriteCanary, githubWriteCanaryPolicy } from './github-write-canary.js';
export { ApprovalConsumptionLedger } from './approval-ledger.js';
function json(body,status=200){return new Response(JSON.stringify(body,null,2),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'}});}
function bearer(request){const h=request.headers.get('authorization')||'';return h.toLowerCase().startsWith('bearer ')?h.slice(7).trim():null;}
function authorized(request,env){return !!env?.SUPERPOWERS_AUTH_TOKEN&&bearer(request)===env.SUPERPOWERS_AUTH_TOKEN;}
async function readJson(request){try{return{ok:true,body:await request.json()};}catch{return{ok:false,response:json({ok:false,error:'invalid_json'},400)};}}
function consumptionLedger(env){if(!env?.APPROVAL_LEDGER)return null;const id=env.APPROVAL_LEDGER.idFromName('global'),stub=env.APPROVAL_LEDGER.get(id);return{async consume(record){const r=await stub.fetch('https://approval-ledger.internal/consume',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(record)});return r.json();}};}
function executorDeps(env){return{approvalSecret:env?.SUPERPOWERS_APPROVAL_SECRET,githubAdapter:githubWriteAdapter(env),async consumeApprovalGrant(grant,approvalRequest,secret){return consumeApprovalGrant(grant,approvalRequest,secret,consumptionLedger(env));}};}
const execute=(body,env)=>executeApprovedGithubWrite(body,executorDeps(env));
export default {async fetch(request,env){const url=new URL(request.url);
if(request.method==='GET'&&url.pathname==='/health')return json({ok:true,service:'tlt-superpowers-router',version:'0.5.0-github-write-canary',mode:'deterministic-routing',auth:{protected_endpoints:['/registry','/route','/approval/prepare','/approval/confirm','/approval/validate','/approval/consume','/github/write/canary','/github/write/execute']},github_write_lane:{approval_grants_available:true,replay_protection:'durable_object_single_use_transactional',ledger_configured:!!env?.APPROVAL_LEDGER,service_binding_configured:!!env?.GITHUB_WRITE,service_token_configured:!!env?.GITHUB_WRITE_INTERNAL_TOKEN,approval_secret_configured:!!env?.SUPERPOWERS_APPROVAL_SECRET,canary_enabled:String(env?.GITHUB_WRITE_CANARY_ENABLED||'false')==='true',generic_execution_enabled:String(env?.GITHUB_WRITE_EXECUTION_ENABLED||'false')==='true',canary_policy:githubWriteCanaryPolicy,delete_permitted:false,archive_permitted:false,merge_permitted:false,force_update_permitted:false},policy:{never_delete_automatically:policies.neverDeleteAutomatically,never_archive_automatically:policies.neverArchiveAutomatically,project_before_capability:policies.projectBeforeCapability,human_approval_before_publication:policies.humanApprovalBeforePublication}});
const protectedPaths=new Set(['/registry','/route','/approval/prepare','/approval/confirm','/approval/validate','/approval/consume','/github/write/canary','/github/write/execute']);if(protectedPaths.has(url.pathname)&&!authorized(request,env))return json({ok:false,error:'unauthorized'},401);
if(request.method==='GET'&&url.pathname==='/registry')return json({projects:projects.map(({keywords,...p})=>p),capabilities:capabilities.map(({keywords,...c})=>c),policies});
if(request.method==='POST'&&url.pathname==='/route'){const p=await readJson(request);if(!p.ok)return p.response;const r=routeRequest(p.body);return json(r,r.ok?200:400);}
if(request.method==='POST'&&url.pathname==='/approval/prepare'){const p=await readJson(request);if(!p.ok)return p.response;const r=await prepareApprovalRequest(p.body);return json(r,r.ok?200:400);}
if(request.method==='POST'&&url.pathname==='/approval/confirm'){const p=await readJson(request);if(!p.ok)return p.response;const r=await issueApprovalGrant(p.body,env?.SUPERPOWERS_APPROVAL_SECRET);return json(r,r.ok?200:400);}
if(request.method==='POST'&&url.pathname==='/approval/validate'){const p=await readJson(request);if(!p.ok)return p.response;const r=await validateApprovalGrant(p.body?.approval_grant,p.body?.approval_request,env?.SUPERPOWERS_APPROVAL_SECRET);return json(r,r.ok?200:400);}
if(request.method==='POST'&&url.pathname==='/approval/consume'){const p=await readJson(request);if(!p.ok)return p.response;const r=await consumeApprovalGrant(p.body?.approval_grant,p.body?.approval_request,env?.SUPERPOWERS_APPROVAL_SECRET,consumptionLedger(env));return json(r,r.ok?200:(r.error==='approval_grant_already_consumed'?409:400));}
if(request.method==='POST'&&url.pathname==='/github/write/canary'){if(String(env?.GITHUB_WRITE_CANARY_ENABLED||'false')!=='true')return json({ok:false,error:'github_write_canary_disabled'},403);const p=await readJson(request);if(!p.ok)return p.response;const c=validateGithubWriteCanary(p.body?.approval_request);if(!c.ok)return json(c,400);const r=await execute(p.body,env);return json(r,r.ok?200:(r.error==='approval_grant_already_consumed'?409:400));}
if(request.method==='POST'&&url.pathname==='/github/write/execute'){if(String(env?.GITHUB_WRITE_EXECUTION_ENABLED||'false')!=='true')return json({ok:false,error:'github_write_execution_disabled',canary_available:String(env?.GITHUB_WRITE_CANARY_ENABLED||'false')==='true',delete_permitted:false,archive_permitted:false},403);const p=await readJson(request);if(!p.ok)return p.response;const r=await execute(p.body,env);return json(r,r.ok?200:(r.error==='approval_grant_already_consumed'?409:400));}
return json({ok:false,error:'not_found'},404);}};
