// GENERATED DEPLOYMENT MIRROR. Canonical: lehr007-coder/Listing-Team-Development-Repository/marketing-superpowers/runtime/src/router.js
import { projects, capabilities, policies } from './registry.js';
const normalize=(text)=>String(text||'').trim().toLowerCase();
function scoreKeywords(text,keywords=[]){let score=0;const matched=[];for(const keyword of keywords){const k=keyword.toLowerCase();if(text.includes(k)){score+=k.includes(' ')?3:1;matched.push(keyword);}}return{score,matched};}
function resolveProject(text,hint){if(hint){const explicit=projects.find(p=>p.id===hint||p.name.toLowerCase()===String(hint).toLowerCase());if(explicit)return{project:explicit,confidence:1,matched:['explicit_project_hint']};}const ranked=projects.map(project=>({project,...scoreKeywords(text,project.keywords)})).sort((a,b)=>b.score-a.score);const best=ranked[0];if(!best||best.score===0)return{project:null,confidence:0,matched:[]};const second=ranked[1]?.score||0;return{project:best.project,confidence:Math.min(.98,.55+best.score*.08+Math.max(0,best.score-second)*.04),matched:best.matched};}
function resolveCapabilities(text,project){const ranked=capabilities.map(capability=>({capability,...scoreKeywords(text,capability.keywords)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score);const selected=ranked.map(x=>({id:x.capability.id,provider:x.capability.provider,domain:x.capability.domain,matched:x.matched}));if(project?.id==='marketing_superpowers'){for(const id of['squarespace','seo_edge','images'])if(!selected.some(x=>x.id===id)){const cap=capabilities.find(x=>x.id===id);selected.push({id:cap.id,provider:cap.provider,domain:cap.domain,matched:['project_default']});}}if(project?.id==='condo_intel'&&!selected.some(x=>x.id==='crm')){const cap=capabilities.find(x=>x.id==='crm');selected.push({id:cap.id,provider:cap.provider,domain:cap.domain,matched:['project_dependency']});}return selected;}
function inferIntent(text){const destructive=['delete','remove','destroy','archive','disable','drop','purge'].some(w=>text.includes(w));const publish=['publish','send','schedule','post','launch','deploy'].some(w=>text.includes(w));const write=destructive||publish||['create','update','change','edit','write','add','sync','push'].some(w=>text.includes(w));return{destructive,publish,write,readOnly:!write};}
function agentPlan(project,text){if(!project)return['orchestrator'];if(project.id==='marketing_superpowers'){const plan=['orchestrator','researcher','strategist','writer'];if(text.includes('seo')||text.includes('blog')||text.includes('website')||text.includes('landing page'))plan.push('seo_aeo');plan.push('fact_compliance','editor','publisher');return plan;}if(project.id==='condo_intel')return['orchestrator','real_estate_data','fact_compliance'];if(project.id==='transaction_os')return['orchestrator','transaction_intelligence','fact_compliance'];if(project.id==='ylopo_intelligence')return['orchestrator','lead_intelligence','fact_compliance'];return['orchestrator'];}
export function routeRequest(input){const request=normalize(input?.request);if(!request)return{ok:false,error:'request_required'};const projectResolution=resolveProject(request,input?.project_hint);const project=projectResolution.project;const selectedCapabilities=resolveCapabilities(request,project);const intent=inferIntent(request);const gates=[];if(intent.destructive)gates.push('BLOCKED_BY_DEFAULT_NO_DELETE_POLICY');if(intent.publish)gates.push('HUMAN_APPROVAL_BEFORE_PUBLICATION');if(intent.write&&project&&policies.strictWriteProjects.includes(project.id))gates.push('STRICT_PROJECT_WRITE_GATE');if(intent.write&&!intent.publish&&!intent.destructive)gates.push('WRITE_APPROVAL_REQUIRED');const canExecuteWithoutApproval=intent.readOnly&&gates.length===0;return{ok:true,request:input.request,intent,project:project?{id:project.id,name:project.name,domain:project.domain,status:project.status,repository:project.repository,write_policy:project.writePolicy,confidence:Number(projectResolution.confidence.toFixed(2)),matched:projectResolution.matched}:null,capabilities:selectedCapabilities,agents:agentPlan(project,request),gates,execution:{mode:canExecuteWithoutApproval?'read_only_safe':'plan_or_wait_for_approval',can_execute_without_approval:canExecuteWithoutApproval,delete_permitted:false,archive_permitted:false},recommendation:project?`Route through ${project.name} first, then use canonical capabilities.`:'No owning project resolved. Use the orchestrator to clarify or perform capability-only routing.'};}
